name: Pull request

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'website/**'
      - 'data/**'
    types: [opened, synchronize]


jobs:
  test-data:
    name: Test Data
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'

      - name: Setup and test
        run: |
          make setup-ci
          make lint-ci
          make build
